supabase/migrations/0000_friendly_frank_castle.sql
supabase/migrations/meta/0000_snapshot.json
supabase/migrations/meta/_journal.json

supabaseのセットアップ

---

src/app/apitest/page.tsx
src/data/comic.ts
src/data/like.ts

漫画の全取得と新着漫画の取得といいね数取得
close #31 #32

漫画の全取得と新着漫画の取得といいね数取得

---

src/app/(pages)/mypage/page.tsx

マイページでデータフェッチ

---

src/app/(pages)/new/page.tsx
src/components/post-edit.tsx
src/components/post-new.tsx

漫画作成ロジックを修正

---

src/app/(pages)/new/page.tsx
src/components/new-page.tsx
src/components/post-edit.tsx

サーバーコンポーネントでラップ

---

src/components/post-new.tsx

refactor: 作成時の画像の削除機能を追加

---

src/app/(pages)/mypage/page.tsx
src/app/(pages)/new/page.tsx
src/app/page.tsx
src/components/hero.tsx
src/components/recommend.tsx
src/components/start-button.tsx

認証してないとページをブロック

---

Dockerfile.prod

fix: 大文字にしろと警告が出たのでその部分を大文字にした

---

src/components/loading.tsx
src/components/post-edit.tsx
src/components/post-new.tsx

/newページの写真投稿部、漫画調整部にそれぞれローディング画面を実装しました。
close

 ローディング画面実装

---

.github/workflows/build-deploy.yaml

chore: envの不具合を修正

---

.github/workflows/build-deploy.yaml

envの不具合を修正

---

.github/workflows/build-deploy.yaml

fix: プロジェクト名を変更

---

src/components/loading.tsx
src/components/new-page.tsx
src/components/post-completed.tsx
src/components/post-edit.tsx
src/components/post-new.tsx
src/components/preview-ichikoma.tsx

newのスタイルを修正

---

.github/workflows/build-deploy.yaml

chore: インフラ用のgithubを編集する処理を追加

---

.github/workflows/build-deploy.yaml

fix: リポジトリ名変更

---

.github/workflows/build-deploy.yaml

chore: インフラ用のgitリポジトリのdockerイメージを変更

---

.github/workflows/build-deploy.yaml

dockerイメージのタグを変更

---

src/auth.ts

trustHostを追加

---

src/db/index.ts

Revert "修正"

---

Dockerfile.prod

fix: dockerfileのホスト名を修正

---

Dockerfile.prod

fix: dockerfileのホスト名を削除

---

Dockerfile.prod
src/components/post-new.tsx

auth_urlを追加

---

.github/workflows/build-deploy.yaml

fix: nextauth_urlを追加

---

.github/workflows/build-deploy.yaml

fix: auth_urlを追加

---

.github/workflows/build-deploy.yaml

fix: authurlを修正

---

.github/workflows/build-deploy.yaml

auth urlを変更

---

.github/workflows/build-deploy.yaml

fix: auth_redirect_proxy_urlを追加

---

.github/workflows/build-deploy.yaml

next_redirect_proxy_urlを追加

---

.github/workflows/build-deploy.yaml
Dockerfile.bun
Dockerfile.prod2
src/auth.ts

実行環境をnodeに変更

---

.github/workflows/build-deploy.yaml
Dockerfile.prod

fix: nextjs.config.mjsをcicdの監視対象に追加

---

.github/workflows/build-deploy.yaml
Dockerfile.prod
next.config.mjs

nextconfigを監視対象に追加

---

Dockerfile.prod
next.config.mjs

fix: standaloneを適応，supabaseのdomainを書き換え

---

.github/workflows/build-deploy.yaml
Dockerfile.prod
next.config.mjs

standaloneを有効，ドメイン書き換え
